version: "2"

services:
  webui:
    image: webui:latest
    build:
      context: ../../webui/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ../../webui/:/usr/src/webui/
      - /usr/src/webui/node_modules
    network_mode: "host"
